#spring:   #自定义静态资源位置
#  mvc:
#    static-path-pattern: /zdy/**
#
#  web:
#    resources:
#      static-locations: classpath:/img/


#  freemarker:      #自定义ftlh位置
#    allow-request-override: false
#    allow-session-override: false
#    cache: false
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: false
#    expose-session-attributes: false
#    suffix: .ftlh  #后缀结尾
#    template-loader-path: classpath:/templates/   #自定义去classpath找 suffix后缀结尾对应的 可以随便更改



spring:  #jsp 的 RequestMapper 前后缀拼接
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp

  datasource:
    url: jdbc:mysql://192.168.31.140:3306/test?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

#mybatis:  #配置mapper xml映射位置
#  mapper-locations: classpath:shitimapper/*.xml  #在resource下的xml
#  type-aliases-package: mycs.daos   #mapper类 所在的包






